services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: >
      sh -c "
      ls &&
      apt update && 
      cd app &&
      npm update &&
      npm run dev
      "
volumes:
  node_modules: